services:
  open_split:
    build: .
    volumes:
      - ./database:/app/database
    ports:
      - "3000:3000"
      - "3002:3001" # host:app
    environment:
      - BACKEND_ADDRESS=http://192.168.1.149:3002