services:
  open_split:
    build: .
    volumes:
      - ./database:/app/database
    ports:
      - "3000:3000"
      - "3002:3001"
    environment:
      - REACT_APP_BACKEND_ADDRESS="http://localhost:3002"