services:
  opensplit:
    container_name: opensplit
    image: ghcr.io/umicorp/opensplit:latest

    volumes:
      - /mnt/user/appdata/opensplit:/app/database # host:container Do not change the app path
    ports:
      - "4000:3000" # Frontend host:container
      - "4001:3001" # Backend host:container
    environment:
      - BACKEND_ADDRESS=https://opbackend.lab.umaidabbasi.com:443 # If using a reverse proxy on the frontend, the backend must also be behind the proxy