services:
  opensplit:
    container_name: opensplit
    image: ghcr.io/umicorp/opensplit:latest

    volumes:
      - /mnt/user/appdata/qbittorrent:/app/database
    ports:
      - "4000:3000"
      - "4001:3001" # host:app
    environment:
      - BACKEND_ADDRESS=https://opbackend.lab.umaidabbasi.com:443